### ISSUE TITLE
无声卡

### ISSUE THREAD

**Issue by BenjaminZWQ001** [Shy07/gigabyte-b365m-rx470-clover#1]
你好，我的配置是 I3 9100， 没有独立显卡
用了你的efi，系统没有声卡呢。

**Comment by Shy07** [comment]
我是独显 HTMI 输出音频的，漏了 AppleACL，下载一个放到 EFI/CLOVER/kexts/Other 就行了

**Comment by Shy07** [comment]
> 我是独显 HTMI 输出音频的，漏了 AppleACL，下载一个放到 EFI/CLOVER/kexts/Other 就行了

已 push 更新，测试耳机和内置扬声器对应机箱前后耳机孔 ok
